version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: |
          python3.6 -m venv venv
          source ./venv/bin/activate
          # pytestインストール
          pip install pytest
          # djangoインストール
          pip install django==2.1.7
          # sphinxインストール
          pip install sphinx
          # pytestコマンド実行
          pytest test_calculations.py --junit-xml=test-results/pytest.xml
          # djangoテスト
          cd cafe/apps
          python manage.py migrate
          python manage.py test
          # HTMLファイルの作成
          make html
          
      # テスト結果を保存する
      - store_test_results:
          path: test-results
      # HTML保存
      - store_artifacts:
          path: _build/html